services:
    npm:
        image: node:22
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        # command: npm run deploy
        command: tail -f /dev/null #idle container
volumes:
    node_modules: