services:
    npm:
        image: node:22
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        restart: unless-stopped
        command: tail -f /dev/null #idle container
volumes:
    node_modules: